language: cpp

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - build-essential
            - coreutils
            - pandoc
            - flex
            - bison
      env:
        - MATRIX_EVAL="NPROC=$(nproc)"
        - DEPLOY_TO_PYPI=true  # Deploy to PyPI only from Linux build.
    - os: osx
      osx_image: xcode11.2
      env:
        - MATRIX_EVAL="NPROC=$(sysctl -n hw.physicalcpu)"

install:
  # We need to install newer versions of Flex and Bison on MacOS X.
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install flex bison gnu-sed; fi

before_script:
  - eval "${MATRIX_EVAL}"
  # We need to use newer versions of Flex and Bison on MacOS X (the ones from Homebrew).
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export CMAKE_INCLUDE_PATH="/usr/local/opt/flex/include"; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export CMAKE_LIBRARY_PATH="/usr/local/opt/flex/lib;/usr/local/opt/bison/lib"; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export PATH="/usr/local/opt/flex/bin:/usr/local/opt/bison/bin:$PATH"; fi

script:
  - ./setup_env.sh
  - source env/bin/activate
  - python3 setup.py build --with-unit-tests
  - python3 setup.py install
  - build/tests/cpp/yaramod_tests
  - pytest -v tests/python

deploy:
  provider: pypi
  skip_cleanup: true
  user: yaramod
  password:
    secure: nwOzwwWlEm2JQ0GHGGeHMUZUz1BfXI4Jc9bCwvy156QFaw/G9gKUYSibR/JGO1SLOn8HgqShNBaOWFgsEF2FLVVqVAe31yID65pnFTWNN60MDxPi+G58Y+uTy79eILyeF8LFByRreB5Oj6i4sl8J/0lHd8DABUYnrYXeVzaTkvI45Rq9cK1511BcQ2/fjgN6rbK90tRChlXAS/253koBxVdXuRPpsJsbTfXS4fuBBtQayi8TjYAZmkxxFyC8v+s+gj1FkBZILNzeZVWPaYmNzjfJ3zrSKsW4Xcdtm8sa3JUrCT1BXvjjAcCjAcIwvkLSvmH3lv+oJusKvxSOtQVwBvVGXMwAhfpBTCTeEYRkxy6ZQz7omjQEIWutg8hf7IcLKHJ1eH773+qsvSf44eN0ZK0BDri3e7hfybPEHZ0893goGBe9a24zdk0LhQ+hPMZGwUtPNipGfaaH3q+AvS9bbhUhjQq5q0zkUv+GLflECB5UopnPBmv3y/Gs6Kgalzyz06ZnGThVfi9usmKEwZem3hx6BRX6YYLgyCfpK269+wPMqDpa3jWr9bNE2zHBKMxv/vqaeQ71uImsH1phFXtxtE79dYiYesMOnZOCfFjsWkicyeKUxyd/UUr/BP8X6XkLNxw0edwPfF7qhNdIcOej+dbwjRfwu+w5M2kHu8pjv8U=
  on:
    tags: true
    condition: $DEPLOY_TO_PYPI = true

branches:
  only:
    # Pushes and PRs to the master branch.
    - master
    # Version tags.
    - /^v?\d+\.\d+.*$/

notifications:
  email:
    on_success: never
